import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Code Snippets App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="px-4 h-12 bg-gray-800 text-white flex items-center">
          <Link href="/" className="text-sm font-semibold">
            {metadata.title as string}
          </Link>
        </header>
        <main className="p-4">{children}</main>
      </body>
    </html>
  );
}
