import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  UserButton,
} from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Code Snippets App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <header className="px-4 h-12 bg-gray-800 text-white flex items-center justify-between">
            <div className="flex items-center">
              <Link href="/" className="text-sm font-semibold">
                {metadata.title as string}
              </Link>
            </div>
            <div className="flex items-center text-sm gap-4">
              <SignedOut>
                <SignInButton />
              </SignedOut>
              <SignedIn>
                <Link
                  href="/new"
                  className="text-white hover:text-gray-200 hover:underline"
                >
                  Create Snippet
                </Link>
                <div className="w-7 flex items-center">
                  <UserButton />
                </div>
              </SignedIn>
            </div>
          </header>
          <main className="p-4">{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
